#!/bin/bash

RED='\033[0;31m'
GREEN='\033[32m'
NC='\033[0m'

if [ -z "$1" ]; then
    echo -e "${RED}[Error]${NC} An input file must be specified!"
    exit 1
fi

FILE="$1"
OUTPUT="${FILE%.c}.ihx"
DIRECTORY=$(dirname "$FILE")

if [ ! -f "$FILE" ]; then
    echo -e "${RED}[Error]${NC} File '$FILE' not found."
    exit 1
fi

sdcc "$FILE" -o "$OUTPUT"
if [ $? -ne 0 ]; then
    echo -e "${RED}[Error]${NC} Compilation failed."
    exit 1
fi

python3 /usr/local/stcgal/stcgal.py -P stc89a "$OUTPUT"
if [ $? -ne 0 ]; then
    echo -e "${RED}[Error]${NC} Flashing failed."
    exit 1
fi

find "$DIRECTORY" -type f ! -name "$(basename "$FILE")" -delete
echo -e "${GREEN}[INFO]${NC} Cleanup done."

echo -e "${GREEN}[INFO]${NC} Operation completed successfully."

